const EMOJIS = [
  { emoji: '😀', name: 'grinning face' },
  { emoji: '😃', name: 'grinning face with big eyes' },
  { emoji: '😄', name: 'grinning face with smiling eyes' },
  { emoji: '😁', name: 'beaming face with smiling eyes' },
  { emoji: '😂', name: 'face with tears of joy' },
  { emoji: '🤣', name: 'rolling on the floor laughing' },
  { emoji: '😅', name: 'grinning face with sweat' },
  { emoji: '😊', name: 'smiling face with smiling eyes' },
  { emoji: '😍', name: 'smiling face with hearts' },
  { emoji: '😘', name: 'face blowing a kiss' },
  { emoji: '😎', name: 'smiling face with sunglasses' },
  { emoji: '😋', name: 'face savoring food' },
  { emoji: '😛', name: 'face with tongue' },
  { emoji: '😜', name: 'winking face with tongue' },
  { emoji: '🤔', name: 'thinking face' },
  { emoji: '🤨', name: 'face with raised eyebrow' },
  { emoji: '😐', name: 'neutral face' },
  { emoji: '😑', name: 'expressionless face' },
  { emoji: '😶', name: 'face without mouth' },
  { emoji: '🙄', name: 'face with rolling eyes' },
  { emoji: '😏', name: 'smirking face' },
  { emoji: '😴', name: 'sleeping face' },
  { emoji: '😷', name: 'face with medical mask' },
  { emoji: '🥵', name: 'hot face' },
  { emoji: '🥶', name: 'cold face' },
  { emoji: '🥴', name: 'woozy face' },
  { emoji: '😵', name: 'knocked-out face' },
  { emoji: '🤯', name: 'exploding head' },
  { emoji: '🥳', name: 'partying face' },
  { emoji: '😭', name: 'loudly crying face' },
  { emoji: '😱', name: 'face screaming in fear' },
  { emoji: '😖', name: 'confounded face' },
  { emoji: '🥱', name: 'yawning face' },
  { emoji: '😡', name: 'pouting face' },
  { emoji: '😠', name: 'angry face' },
  { emoji: '💩', name: 'pile of poo' },
  { emoji: '👻', name: 'ghost' },
  { emoji: '💀', name: 'skull' },
  { emoji: '👽', name: 'alien' },
  { emoji: '🤖', name: 'robot' },
  { emoji: '😺', name: 'grinning cat' },
  { emoji: '👏', name: 'clapping hands' },
  { emoji: '🙌', name: 'raising hands' },
  { emoji: '👐', name: 'open hands' },
  { emoji: '🤲', name: 'palms up together' },
  { emoji: '🤝', name: 'handshake' },
  { emoji: '👍', name: 'thumbs up' },
  { emoji: '👎', name: 'thumbs down' },
  { emoji: '👊', name: 'oncoming fist' },
  { emoji: '✊', name: 'raised fist' },
  { emoji: '🤛', name: 'left-facing fist' },
  { emoji: '🤜', name: 'right-facing fist' },
  { emoji: '🤞', name: 'crossed fingers' },
  { emoji: '✌️', name: 'victory hand' },
  { emoji: '🤟', name: 'love-you gesture' },
  { emoji: '🤘', name: 'sign of the horns' },
  { emoji: '👌', name: 'ok hand' },
  { emoji: '👈', name: 'backhand index pointing left' },
  { emoji: '👉', name: 'backhand index pointing right' },
  { emoji: '👆', name: 'backhand index pointing up' },
  { emoji: '👇', name: 'backhand index pointing down' },
  { emoji: '☝️', name: 'index pointing up' },
  { emoji: '✋', name: 'raised hand' },
  { emoji: '🖐️', name: 'hand with fingers splayed' },
  { emoji: '🖖', name: 'vulcan salute' },
  { emoji: '👋', name: 'waving hand' },
  { emoji: '🤙', name: 'call me hand' },
  { emoji: '💪', name: 'flexed biceps' },
  { emoji: '🙏', name: 'folded hands' },
  { emoji: '🧠', name: 'brain' },
  { emoji: '👀', name: 'eyes' },
  { emoji: '👅', name: 'tongue' },
  { emoji: '👄', name: 'mouth' },
  { emoji: '❤️', name: 'red heart' },
  { emoji: '💔', name: 'broken heart' },
  { emoji: '❣️', name: 'heart exclamation' },
  { emoji: '💕', name: 'two hearts' },
  { emoji: '✨', name: 'sparkles' },
  { emoji: '🔥', name: 'fire' },
  { emoji: '💥', name: 'collision' },
  { emoji: '💯', name: 'hundred points' },
  { emoji: '💢', name: 'anger symbol' },
  { emoji: '💨', name: 'dashing away' },
  { emoji: '💦', name: 'sweat droplets' },
  { emoji: '🐶', name: 'dog face' },
  { emoji: '🐱', name: 'cat face' },
  { emoji: '🐭', name: 'mouse face' },
  { emoji: '🐹', name: 'hamster face' },
  { emoji: '🐰', name: 'rabbit face' },
  { emoji: '🦊', name: 'fox face' },
  { emoji: '🐻', name: 'bear face' },
  { emoji: '🐼', name: 'panda face' },
  { emoji: '🐨', name: 'koala face' },
  { emoji: '🐯', name: 'tiger face' }
]
